version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3"
        NODE_VERSION: "none"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - flask_app
    ports:
      - "5000:5000" # app port
      - "5001:5001" # app(debug) port
      - "3000:3000" # remote debugger attach port
      
  # MySQL服务
  db:
    container_name: postgres_container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: myapp
      MYSQL_USER: palk
      MYSQL_PASSWORD: Admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "palk", "-pAdmin123"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql-data:
